apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-deploy
  labels:
    app: cc-assignment
  annotations:
spec:
  selector:
    matchLabels:
      app: cc-assignment
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cc-assignment
    spec:
      containers:
        - name: cc-assignment
          image: sachiniepa/nodejs:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"