apiVersion: v1
kind: Service
metadata:
  name: cc-service
  labels:
    app: cc-assignment
spec:
  type: ClusterIP
  selector:
    app: cc-assignment
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000